omkbd/ergodash/rev1: Add hand_swap_config
In my fork with qmk 288808526b663c96a1ae2aa6dda96f6a963e470a merged in,
swap-hands was working without an explicitly-defined `hand_swap_config`.

After merging qmk 0.24.8, the build started failing with:
```
Linking: .build/omkbd_ergodash_rev1_vozhyk-.elf                                                     [ERRORS]
 |
 | /usr/libexec/gcc/avr/ld: .build/obj_omkbd_ergodash_rev1_vozhyk-/quantum/action.o: in function `process_hand_swap':
 | /home/vozhyk/dev/c/qmk/quantum/action.c:192: undefined reference to `hand_swap_config'
 | /usr/libexec/gcc/avr/ld: /home/vozhyk/dev/c/qmk/quantum/action.c:192: undefined reference to `hand_swap_config'
 | /usr/libexec/gcc/avr/ld: /home/vozhyk/dev/c/qmk/quantum/action.c:193: undefined reference to `hand_swap_config'
 | /usr/libexec/gcc/avr/ld: /home/vozhyk/dev/c/qmk/quantum/action.c:193: undefined reference to `hand_swap_config'
 | collect2: error: ld returned 1 exit status
 |
gmake: *** [builddefs/common_rules.mk:280: .build/omkbd_ergodash_rev1_vozhyk-.elf] Error 1
```

Add an explicitly-denifed `hand_swap_config`.

Still, I could not find the cause of the change:

Bisecting did not pinpoint a satisfactory commit as the cause:
690792eca9 good
be66e5f2b4 good
7e27d72cbc good
a886d7e3dd bad
094357c403 bad
3a74fa5bf7 good
f96a7bbd63 bad
4601f339e4 good
3ef06aa732 bad
The last commit in the list was found to be the first bad commit,
but reverting the commit did not resolve the issue.

Bisecting was done with the following done on each step:
- `git merge ergodash-vozhyk-old` (23224ef07627c593a3ac2f563d128e6d197f4af9)
- `git reset HEAD lib/chibios lib/chibios-contrib lib/googletest lib/lufa lib/printf lib/vusb`
- `git rm keyboards/omkbd/ergodash/rev1/rev1.c` (when required)
- `git commit --no-edit`
- `git cherry-pick ergodash-vozhyk~3..ergodash-vozhyk`
  (not all of the changes were required+applied every time):
  - c6523166c8 Replace KC_{L,R}SHIFT -> KC_{L,R}SFT
  - e7d86cbdf5 Stop using IGNORE_MOD_TAP_INTERRUPT
  - 379a38ce1b keymap_belarusian_latin: Use keycodes.h
- `qmk compile`